# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("\n"
"    /* 主窗口背景 */\n"
"    QMainWindow {\n"
"        background-color: #2a2a4a;\n"
"        padding: 20px;\n"
"    }\n"
"    \n"
"    /* 通用按钮样式 */\n"
"    QPushButton {\n"
"        background-color: #16213e;\n"
"        color: #e2e2e2;\n"
"        border: 1px solid #0f3460;\n"
"        border-radius: 8px;\n"
"        padding: 10px 20px;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        text-align: left;\n"
"        padding-left: 15px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #0f3460;\n"
"        border-color: #e94560;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #e94560;\n"
"    }\n"
"    \n"
"    /* 提交按钮特殊样式 */\n"
"    QPushButton#pushButton_3 {\n"
"        background-color: #e94560;\n"
"        border-color: #e94560;\n"
"        text-align: center;\n"
"        font-size: 18px;\n"
"        padding: 12px;\n"
"    }\n"
"    QPushButton#pushButton_3:hover {\n"
"        background-color: #ff6b6b;\n"
"    }\n"
"    \n"
"    /* 标签样式 - 字体放大2倍 */\n"
"    QLabel {\n"
"        color: #e2e2e2;\n"
"        font-size: 16px;\n"
"    }\n"
"    /* 标题 - 保持之前的放大效果 */\n"
"    QLabel#label {\n"
"        font-size: 42px;\n"
"        font-weight: bold;\n"
"        color: #e94560;\n"
"        letter-spacing: 3px;\n"
"    }\n"
"    /* 分组标题标签 */\n"
"    QLabel#label_2, QLabel#label_4, QLabel#label_5 {\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        background-color: #3a6ea5;\n"
"        border-radius: 6px;\n"
"        padding: 6px;\n"
"        color: white;\n"
"    }\n"
"    \n"
"    /* 单选框样式 */\n"
"    QRadioButton {\n"
"        color: #e2e2e2;\n"
"        font-size: 14px;\n"
"        spacing: 8px;\n"
"    }\n"
"    QRadioButton::indicator {\n"
"        width: 14px;\n"
"        height: 14px;\n"
"        border-radius: 7px;\n"
"    }\n"
"    QRadioButton::indicator:unchecked {\n"
"        background-color: #16213e;\n"
"        border: 1px solid #0f3460;\n"
"    }\n"
"    QRadioButton::indicator:checked {\n"
"        background-color: #e94560;\n"
"        border: 1px solid #e94560;\n"
"    }\n"
"    \n"
"    /* 滚动区域样式 */\n"
"    QScrollArea {\n"
"        border: 1px solid #0f3460;\n"
"        border-radius: 8px;\n"
"        background-color: #1a1a3a;\n"
"    }\n"
"    \n"
"    /* 状态标签 - 字体放大 */\n"
"    QLabel#label_3 {\n"
"        background-color: #1a1a3a;\n"
"        border: 1px solid #0f3460;\n"
"        border-radius: 8px;\n"
"        padding: 12px;\n"
"        font-family: monospace;\n"
"        font-size: 14px;\n"
"    }\n"
"    \n"
"    /* 分组面板样式 - 更浅的蓝色背景 */\n"
"    QWidget#resolution_widget, QWidget#mode_widget {\n"
"        background-color: #3a6ea5;\n"
"        border-radius: 10px;\n"
"        padding: 10px;\n"
"    }\n"
"    /* 分组面板内的标签文字颜色 */\n"
"    QWidget#resolution_widget QLabel, QWidget#mode_widget QLabel {\n"
"        color: white;\n"
"        font-weight: bold;\n"
"    }\n"
"    /* 分组面板内的单选框文字颜色 */\n"
"    QWidget#resolution_widget QRadioButton, QWidget#mode_widget QRadioButton {\n"
"        color: white;\n"
"        font-size: 14px;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(800, 20, 320, 70))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.toolButton_4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_4.setGeometry(QtCore.QRect(1830, 15, 40, 35))
        self.toolButton_4.setStyleSheet("background-color: #0f3460; border-radius: 6px; color: white; font-weight: bold; font-size: 18px;")
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(1875, 15, 40, 35))
        self.toolButton_3.setStyleSheet("background-color: #e94560; border-radius: 6px; color: white; font-weight: bold; font-size: 18px;")
        self.toolButton_3.setObjectName("toolButton_3")
        self.widget_2 = QVideoWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(30, 100, 580, 300))
        self.widget_2.setStyleSheet("border: 2px solid #0f3460; border-radius: 10px; background-color: #000000;")
        self.widget_2.setObjectName("widget_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 410, 580, 300))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setStyleSheet("border: 1px solid #0f3460; border-radius: 8px;")
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 578, 298))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gallery_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gallery_widget.setObjectName("gallery_widget")
        self.verticalLayout_3.addWidget(self.gallery_widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 60, 140, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 370, 140, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 740, 140, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.resolution_widget = QtWidgets.QWidget(self.centralwidget)
        self.resolution_widget.setGeometry(QtCore.QRect(30, 810, 160, 110))
        self.resolution_widget.setObjectName("resolution_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.resolution_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.resolution_widget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.radioButton = QtWidgets.QRadioButton(self.resolution_widget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.resolution_widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 740, 100, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 775, 430, 160))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.mode_widget = QtWidgets.QWidget(self.centralwidget)
        self.mode_widget.setGeometry(QtCore.QRect(680, 100, 180, 110))
        self.mode_widget.setStyleSheet("background-color: #3a6ea5; border-radius: 10px; padding: 8px;")
        self.mode_widget.setObjectName("mode_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mode_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.mode_widget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.radioButton_3 = QtWidgets.QRadioButton(self.mode_widget)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.mode_widget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.widget_3 = VTKWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(700, 220, 1180, 820))
        self.widget_3.setStyleSheet("border: 2px solid #0f3460; border-radius: 10px; background-color: #0f0f1a;")
        self.widget_3.setObjectName("widget_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3D重建系统"))
        self.label.setText(_translate("MainWindow", "🎨 3D重建"))
        self.toolButton_4.setText(_translate("MainWindow", "─"))
        self.toolButton_3.setText(_translate("MainWindow", "✕"))
        self.pushButton.setText(_translate("MainWindow", "📷 上传图片"))
        self.pushButton_2.setText(_translate("MainWindow", "🎬 上传视频"))
        self.pushButton_3.setText(_translate("MainWindow", "🚀 开始重建"))
        self.label_4.setText(_translate("MainWindow", "📐 图像分辨率"))
        self.radioButton.setText(_translate("MainWindow", "512 (高精度)"))
        self.radioButton_2.setText(_translate("MainWindow", "224 (快速)"))
        self.label_2.setText(_translate("MainWindow", "⚙️ 处理状态"))
        self.label_3.setText(_translate("MainWindow", "等待上传图片或视频..."))
        self.label_5.setText(_translate("MainWindow", "🖱️ 交互模式"))
        self.radioButton_3.setText(_translate("MainWindow", "🔍 选点模式"))
        self.radioButton_4.setText(_translate("MainWindow", "📏 连线模式"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
from VTK_Widget import VTKWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
